# This env file should be kept in sync with conda3_bleed-osx-64.txt
# future + pyyaml are lsst-build deps. See DM-15025
name: bleed
channels:
  - conda-forge
  - defaults
dependencies:
  # build dependencies
  - pytest
  - pytest-cov
  - pytest-xdist
  # host dependencies
  - astropy
  - boto3
  - bottleneck
  - cffi
  - click
  - cython
  - deprecated
  - future
  - h5py
  - matplotlib
  - moto
  - numexpr
  - numpy
  - pandas
  - pip
  - pyarrow
  - pytables
  - python
  - pyyaml
  - requests
  - scikit-learn
  - scipy
  - sqlalchemy
  # run dependencies
  - pip:
    - pytest-subtests
