# NOTE: These files are deprecated and not guaranteed to be installable.
name: gpoc
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - apipkg=1.5
  - appdirs=1.4.3
  - apr=1.6.5
  - arrow-cpp=0.16.0
  - asn1crypto=1.3.0
  - asteval=0.9.16
  - astropy=4.0.1.post1
  - attrs=19.3.0
  - autograd=1.3
  - aws-sam-translator=1.23.0
  - aws-sdk-cpp=1.7.164
  - aws-xray-sdk=0.95
  - backports=1.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - binutils-meta=1.0.4
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - blosc=1.18.1
  - boost=1.70.0
  - boost-cpp=1.70.0
  - boto=2.49.0
  - boto3=1.13.17
  - botocore=1.16.17
  - bottleneck=1.3.2
  - brotli=1.0.7
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.15.0
  - c-compiler=1.0.4
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cfitsio=3.470
  - cfn-lint=0.24.4
  - chardet=3.0.4
  - click=7.0
  - cloudpickle=1.4.1
  - cmake=3.17.0
  - compilers=1.0.4
  - cookies=2.2.1
  - coverage=5.1
  - cryptography=2.9.2
  - curl=7.69.1
  - cxx-compiler=1.0.4
  - cycler=0.10.0
  - cython=0.29.19
  - cytoolz=0.10.1
  - dask-core=2.16.0
  - dbus=1.13.6
  - decorator=4.4.2
  - deprecated=1.2.10
  - docker-py=4.2.0
  - docker-pycreds=0.4.0
  - docutils=0.15.2
  - doxygen=1.8.18
  - ecdsa=0.13
  - eigen=3.3.7
  - entrypoints=0.3
  - esutil=0.6.4
  - execnet=1.7.1
  - expat=2.2.9
  - fastavro=0.23.4
  - fftw=3.3.8
  - fitsio=1.1.2
  - flake8=3.7.9
  - flake8-polyfill=1.0.2
  - flask=1.1.2
  - fontconfig=2.13.1
  - fortran-compiler=1.0.4
  - freetype=2.10.2
  - future=0.18.2
  - galsim=2.2.4
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - git=2.26.2
  - git-lfs=2.11.0
  - glib=2.64.3
  - glog=0.4.0
  - grpc-cpp=1.25.0
  - gsl=2.6
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - h5py=2.10.0
  - hdf5=1.10.5
  - healpy=1.13.0
  - icu=58.2
  - idna=2.8
  - imagecodecs-lite=2019.12.3
  - imageio=2.8.0
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - itsdangerous=1.1.0
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.15.1
  - jpeg=9c
  - jsondiff=1.1.2
  - jsonpatch=1.24
  - jsonpickle=1.4.1
  - jsonpointer=2.0
  - jsonschema=3.2.0
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lapack=3.6.1
  - ld_impl_linux-64=2.34
  - libapr=1.6.5
  - libapriconv=1.2.2
  - libaprutil=1.6.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.69.1
  - libedit=3.1.20170329
  - libevent=2.1.10
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.5.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libprotobuf=3.11.0
  - libssh2=1.9.0
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libuv=1.38.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.9
  - llvm-openmp=10.0.0
  - lmfit=1.0.0
  - log4cxx=0.10.0
  - lsstdesc.coord=1.2.1
  - lz4-c=1.8.3
  - lzo=2.10
  - make=4.3
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mccabe=0.6.1
  - minuit2=6.18.00
  - minuit2_standalone=6.18.00
  - mock=4.0.2
  - more-itertools=8.3.0
  - moto=1.3.14
  - mpi=1.0
  - mpi4py=3.0.2
  - mpich=3.2.1
  - ncurses=6.1
  - ndarray=1.5.3
  - networkx=2.4
  - numexpr=2.7.1
  - numpy=1.18.4
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.3
  - parquet-cpp=1.5.1
  - pcre=8.44
  - pep8-naming=0.10.0
  - perl=5.26.2
  - pgplot=5.2.2
  - pillow=7.1.2
  - pip=20.1.1
  - pluggy=0.13.1
  - psutil=5.7.0
  - pthread-stubs=0.4
  - py=1.8.1
  - pyarrow=0.16.0
  - pybind11=2.2.4
  - pycodestyle=2.5.0
  - pycparser=2.20
  - pyflakes=2.1.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=5.4.2
  - pytest-cov=2.9.0
  - pytest-doctestplus=0.6.1
  - pytest-flake8=1.0.6
  - pytest-forked=1.1.2
  - pytest-runner=5.2
  - pytest-session2file=0.1.9
  - pytest-subtests=0.3.1
  - pytest-xdist=1.32.0
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-jose=3.1.0
  - python_abi=3.7
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.9.7
  - re2=2020.04.01
  - readline=8.0
  - requests=2.23.0
  - responses=0.10.14
  - rhash=1.3.6
  - s3transfer=0.3.3
  - scikit-image=0.17.2
  - scikit-learn=0.23.1
  - scipy=1.4.1
  - scons=3.1.2
  - setuptools=46.4.0
  - sip=4.19.8
  - six=1.15.0
  - snappy=1.1.8
  - sqlalchemy=1.3.17
  - sqlite=3.30.1
  - sshpubkeys=3.1.0
  - starlink-ast=9.1.0
  - threadpoolctl=2.0.0
  - thrift-cpp=0.12.0
  - tifffile=2020.5.11
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - treecorr=3.3.11
  - uncertainties=3.1.2
  - urllib3=1.25.9
  - wcslib=7.2
  - wcwidth=0.1.9
  - websocket-client=0.57.0
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - ws4py=0.5.1
  - xmltodict=0.12.0
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-xproto=7.0.31
  - xpa=2.1.20
  - xz=5.2.5
  - yaml=0.2.4
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
