# This env file should be kept in sync with conda3_bleed-osx-64.txt
# future + pyyaml are lsst-build deps. See DM-15025
name: bleed
channels:
  - conda-forge
  - defaults
dependencies:
  # build dependencies
  - compilers
  - cmake
  - doxygen
  - flake8 <3.8
  - git
  - git-lfs
  - make
  - pep8-naming
  - psutil
  - pytest
  - pytest-cov
  - pytest-doctestplus
  - pytest-flake8
  - pytest-runner
  - pytest-session2file <=0.1.9
  - pytest-subtests
  - pytest-xdist
  - scons
  - setuptools =46.4
  # host dependencies
  - apr
  - autograd
  - astropy
  - boost =1.70
  - boto3
  - bottleneck
  - cffi
  - cfitsio
  - click <7.1
  - cython
  - deprecated
  - eigen
  - esutil
  - fastavro
  - future
  - galsim
  - gsl
  - h5py
  - healpy
  - libaprutil
  - lapack
  - log4cxx
  - lmfit
  - lsstdesc.coord
  - matplotlib =3.0
  - minuit2
  - moto
  - mpich =3.2.1
  - mpi4py
  - ndarray
  - numexpr
  - numpy
  - pandas
  - pip
  - pyarrow
  - pybind11 <2.3
  - pyqt <5.12 # For matplotlib on linux. See https://github.com/conda-forge/pyqt-feedstock/issues/77
  - pytables
  - python
  - pyyaml
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - starlink-ast
  - sqlalchemy
  - treecorr <4
  - wcslib
  - ws4py
  - xpa
  # run dependencies
