name: pinnedver_qserv_20200518
channels:
  - conda-forge
  - defaults
dependencies:
  - compilers=1.0.4
  - cmake=3.17.0
  - doxygen=1.8.18
  - flake8=3.7.9
  - git=2.26.2
  - git-lfs=2.11.0
  - make=4.3
  - pep8-naming=0.10.0
  - psutil=5.7.0
  - pytest=5.4.2
  - pytest-cov=2.8.1
  - pytest-doctestplus=0.6.1
  - pytest-flake8=1.0.6
  - pytest-runner=5.2
  - pytest-session2file=0.1.9
  - pytest-xdist=1.32.0
  - scons=3.1.2
  # host dependencies
  - apr=1.6.5
  - autograd=1.3
  - astropy=4.0.1.post1
  - boost=1.70.0
  - boto3=1.13.11
  - bottleneck=1.3.2
  - cffi=1.14.0
  - cfitsio=3.470
  - click=7.0
  - cython=0.29.17
  - deprecated=1.2.10
  - eigen=3.3.7
  - esutil=0.6.4
  - fastavro=0.23.4
  - future=0.18.2
  - galsim=2.2.4
  - gsl=2.6
  - h5py=2.10.0
  - healpy=1.13.0
  - libaprutil=1.6.1
  - lapack=3.6.1
  - log4cxx=0.10.0
  - lmfit=1.0.0
  - lsstdesc.coord=1.2.1
  - matplotlib=3.0.3
  - minuit2=6.18.00
  - moto=1.3.14
  - mpich=3.2.1
  - mpi4py=3.0.2
  - ndarray=1.5.3
  - numexpr=2.7.1
  - numpy=1.18.4
  - pandas=1.0.3
  - pip=20.1
  - pyarrow=0.16.0
  - pybind11=2.2.4
  - pyqt=5.9.2
  - pytables=3.6.1
  - python=3.7.6
  - pyyaml=5.3.1
  - requests=2.23.0
  - scikit-image=0.17.2
  - scikit-learn=0.23.0
  - scipy=1.4.1
  - starlink-ast=9.1.0
  - sqlalchemy=1.3.17
  - treecorr=3.3.11
  - wcslib=7.2
  - ws4py=0.5.1
  - xpa=2.1.20
  # qserv dependencies
  - flex=2.6.4
  - jemalloc=5.2.1
  - mysqlclient=1.4.6
  - nlohmann_json=3.7.3
  - openjdk=11.0.1
  - pkg-config=0.29.2
  - protobuf=3.11.0
  - pymysql=0.9.3
  # run dependencies
  # pip dependencies
  - pip:
    - peigen==0.0.9
    - pytest-subtests==0.3.0
