name: default
channels:
  - conda-forge
  - defaults
dependencies:
  # build
  - make
  - scons
  - git-lfs
  # link
  - apr
  - boost
  - bottleneck
  - cfitsio
  - deprecated
  - doxygen
  - eigen
  - fftw
  - galsim
  - gsl
  - libaprutil
  - liblapacke # For psfex
  - log4cxx
  - lmfit
  - minuit2
  - mpi4py
  - mpich
  - ndarray
  - numexpr
  - starlink-ast
  - treecorr
  - wcslib
  # python
  - astropy
  - cffi
  - cython
  # - esutil # FIXME: When esutil is updated
  - flake8
  - future
  - h5py
  - healpy
  - matplotlib
  - numpy
  - pandas
  - pep8-naming
  - pip
  - pytables
  - pytest
  - pytest-cov
  - pytest-flake8
  - pytest-forked
  - pytest-xdist
  - pyyaml
  - requests
  - scikit-learn
  - scipy
  - sqlalchemy
  - ws4py
  # Pins
  - pybind11 < 2.3
  - pip:
    - git+https://github.com/fabricecoulon/pytest_session2file@fix_for_python3
