# This env file should be kept in sync with conda3_bleed-osx-64.txt
# future + pyyaml are lsst-build deps. See DM-15025
name: bleed-qserv
channels:
  - conda-forge
  - defaults
dependencies:
  # build dependencies
  - compilers
  - cmake
  - doxygen
  - flake8 <3.8
  - git
  - git-lfs
  - make
  - pep8-naming
  - psutil
  - pytest <6
  - pytest-cov
  - pytest-doctestplus !=0.7.0
  - pytest-flake8
  - pytest-runner
  - pytest-session2file !=0.1.10
  - pytest-subtests
  - pytest-xdist
  - scons
  # host dependencies
  - boost =1.70
  - deprecated
  - future
  - log4cxx
  - pip
  - pybind11
  - python >=3.7
  - pyyaml
  - requests
  - sqlalchemy
  # run dependencies
  # qserv dependencies
  - flex
  - jemalloc
  - libevent
  - mysqlclient
  - nlohmann_json
  - openjdk
  - pkg-config
  - protobuf =3.14
  - pymysql

