# This env file should be kept in sync with conda3_bleed-osx-64.txt with the
# exception of the nomkl being present on linux and NOT on osx.
# nomkl is required on linux.  See DM-8146
# future + pyyaml are lsst-build deps. See DM-15025
name: bleed
channels:
  - defaults
dependencies:
  - astropy
  - boto3
  - bottleneck
  - cffi
  - click
  - cython
  - deprecated
  - future
  - h5py
  - matplotlib
  - moto
  - nomkl
  - numexpr
  - numpy
  - pandas
  - pyarrow
  - pip
  - pytables
  - pytest
  - pytest-cov
  - pytest-xdist
  - python
  - pyyaml
  - requests
  - scikit-learn
  - scipy
  - sqlalchemy
  - pip:
    - pytest-subtests
