# This env file should be kept in sync with conda3_bleed-osx-64.txt
# future + pyyaml are lsst-build deps. See DM-15025
name: bleed-qserv
channels:
  - conda-forge
  - defaults
dependencies:
  # build dependencies
  - compilers
  - cmake
  - doxygen
  - flake8
  - git
  - git-lfs
  - jq
  - make
  - pep8-naming
  - psutil
  - pytest
  - pytest-cov
  - pytest-doctestplus
  - pytest-flake8
  - pytest-runner
  - pytest-session2file
  - pytest-subtests
  - pytest-xdist
  - scons
  # host dependencies
  - boost <=1.74
  - click
  - deprecated
  - future
  - healpy
  - log4cxx =0
  - pip
  - pybind11
  - python >=3.8
  - pyyaml
  - requests
  - sqlalchemy
  # run dependencies
  # qserv dependencies
  - flask
  - flex
  - glib
  - jemalloc
  - libevent
  - mysqlclient
  - nlohmann_json
  - openjdk
  - pkg-config
  - protobuf
  - pymysql

